### ISSUE TITLE
Reactions/Feedback support for Youtube's live api

### ISSUE THREAD

**Issue by FrancoBM12** [googleapis/google-api-java-client-services#22458]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
So, I find myself using the Youtube live API to get the live chat messages but I would also like to be able to get the reactions/feedback that have been given in the moment or even the likes that have been given in the live.

**Describe the solution you'd like**
Adding methods to YouTube Data API v3 that include these needs

**Describe alternatives you've considered**
--

**Additional context**
I know Youtube is probably not dedicated to Lives like other platforms but improving the API by allowing us to access more live data would be great to make lives a bit more interactive and out of the ordinary.

**Comment by zhumin8** [comment]
Thanks for reporting with us. However, your request sounds like a feature request to the service. Note that this repo is only providing the client surface and the maintainers are not familiar the service itself.
If you have support contract, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. Otherwise, perhaps issue tracker or other support channel listed in [this page](https://developers.google.com/youtube/v3/support) can get your request closer to the service team.
