### ISSUE TITLE
FHIR healthcare objects missing from this?

### ISSUE THREAD

**Issue by deanorderly** [googleapis/google-api-java-client-services#4515]
there is a github/google/fhir repo that I can only assume google healthcare api is using as it has the proto files.  I can't seem to use artman to generate from that repo AND can't file issues on that repo as there is no issues tab.

Why is the fhir objects at least not in this repo?  Any pointers to getting the google cloud healthcare FHIR compliant java protobuf objects (that can do FHIR json for healthcare compliance) would ROCK!!!! but I can't seem to find the right repo or generator or something!

thanks for any pointers!!!

**Comment by danoscarmike** [comment]
@nickgeorge might you be able to help here?

**Comment by nickgeorge** [comment]
Hi Folks, sorry for slow response, I still a little new to maintaining open source :)

So currently, the library is designed to work with bazel build system - the proto definitions themselves are at @com_google_proto//fhir/proto, e.g., 
https://github.com/google/fhir/blob/master/proto/r4/core/resources/patient.proto
Therefore, we don't package the protos compiled into java in the repo, since we assume bazel generates them as a part of the build. 

However, we are very close to releasing all the Java protos + library code as a Maven jar - would that solve your needs?

Thanks,
NIck
--

**Comment by deanorderly** [comment]
yes, being able to depend on maven would rock!!!

thanks,
Dean

**Comment by meredithslota** [comment]
Just to follow-up, the Cloud Healthcare API client library is here: https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-healthcare/v1 and it does look like you can use Maven. :)
