### ISSUE TITLE
Google Calendar Event Creation send Notifications

### ISSUE THREAD

**Issue by renatoborgescardoso** [googleapis/google-api-java-client-services#4657]
Event creation does not send email. The calendar event is created.
Exemple: 
service.events().insert(calendarId, event).setSendUpdates("all").execute();    or 
service.events().insert(calendarId, event).setSendNotifications(Boolean.TRUE).execute();

**Comment by burkedavison** [comment]
Closing this issue as we are unable to provide adequate customer support through this forum. If you feel there is a bug or a feature request associated with this ticket, please open a new issue. Otherwise, https://cloud.google.com/support is best able to provide timely answers to API-specific questions.
