### ISSUE TITLE
Android Studio Update Suggestion

### ISSUE THREAD

**Issue by MaxAndolini** [googleapis/google-api-java-client-services#6077]
I implemented this android publisher. But Android Studio suggests me to update v1 version.

`implementation 'com.google.apis:google-api-services-androidpublisher:v3-rev20200927-1.30.10'`

![Screenshot_1](https://user-images.githubusercontent.com/6771759/95481906-3a224180-0996-11eb-8588-177d78d6448f.png)

**Comment by burkedavison** [comment]
Closing this issue as we are unable to provide adequate customer support through this forum. If you feel there is a bug or a feature request associated with this ticket, please open a new issue. Otherwise, https://cloud.google.com/support is best able to provide timely answers to API-specific questions.
